language: go
dist: xenial

go:
- 1.16.x
- master

addons:
  sonarcloud:
    organization: "ulboralabs" # the key of the org you chose at step #3    
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner